### ISSUE TITLE
Add extra info to release workflow

### ISSUE THREAD

**Issue by TB-DevAcc** [jo-jstrm/SmartHomeBuddy#52]
Such as:

``` yml
with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
```
